### ISSUE TITLE
As a parent I want know how many participants / groups there are. So that I know if there are many participants, but their divided into smaller groups, etc.

### ISSUE THREAD

**Issue by ingrskar** [ung-it/UngIT#39]
Priority: 70

**Comment by skaugvoll** [comment]
Due to research, this issue was not implemented!

This issue originated after the first workshop, and then it was presented as an information that was useful, BUT after the last focus group with family, it became apparent that it was unnecessary and would not work because it puts more follow-up moments than answers. Thus, this is no longer relevant.
